// Re-export Prisma types to ensure they are properly recognized
export {
  ProrrateMethod,
  ExpenseStatus,
  PaymentStatus,
  PaymentMethod,
  UserStatus,
  RoleName,
  PlanType,
  UnitType,
  UserUnitStatus,
  ParcelStatus,
  VisitorStatus,
  AnnouncementType,
  DocumentCategory,
  CommunicationType,
  ReservationStatus,
  IncidentStatus,
  CommunityType,
} from '@prisma/client';

// Re-export Prisma client types
export type {
  Prisma,
  PrismaClient,
  Organization,
  Community,
  CommunityCommonSpace,
  Unit,
  User,
  Role,
  UserRole,
  CommunityAdmin,
  UserUnit,
  Expense,
  Payment,
  CommunityExpense,
  CommunityExpenseItem,
  Parcel,
  Visitor,
  Announcement,
  Document,
  Communication,
  SpaceReservation,
  Incident,
} from '@prisma/client';
